# Generated by Django 4.2.7 on 2026-03-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Charge in Indian Rupees (₹)', max_digits=10),
        ),
    ]
