# Generated by Django 4.2.7 on 2026-03-19 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_labreport_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=255)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('WORKING', 'Working'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('OUT_OF_ORDER', 'Out of Order')], default='WORKING', max_length=20)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lab_equipment',
            },
        ),
        migrations.CreateModel(
            name='LabTestCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('test_code', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('BLOOD', 'Blood Test'), ('URINE', 'Urine Test'), ('IMAGING', 'Imaging'), ('CARDIO', 'Cardiology'), ('BIOCHEMISTRY', 'Biochemistry'), ('MICROBIOLOGY', 'Microbiology'), ('HORMONE', 'Hormone Assay'), ('SEROLOGY', 'Serology'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('normal_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('normal_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('normal_range_text', models.CharField(blank=True, help_text="e.g., 'Negative' or 'See individual parameters'", max_length=255, null=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sample_type', models.CharField(blank=True, max_length=100, null=True)),
                ('preparation_instructions', models.TextField(blank=True, null=True)),
                ('turnaround_time', models.CharField(blank=True, help_text="e.g., '24-48 hours'", max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lab Test Catalog',
                'verbose_name_plural': 'Lab Test Catalog',
                'db_table': 'lab_test_catalog',
            },
        ),
        migrations.AlterField(
            model_name='labrequest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='laboratory.labtestcatalog'),
        ),
        migrations.DeleteModel(
            name='LabTestType',
        ),
    ]
